### ISSUE TITLE
Not working for all URLs on Amazon

### ISSUE THREAD

**Issue by rothsandro** [rishijash/DontRefMe#1]
Unfortunately, it's not working for all URLs. It just removes all query parameters, which does not always work.

**Input**  
https://www.amazon.de/b/?node=17109986031&pf_rd_p=3e366c24-d338-4855-8033-3fa8f7e3ab96&pf_rd_r=Z5NRX0VYV0ED2DNHHV3J

**Expected Output**  
https://www.amazon.de/b/?node=17109986031

**Actual Output**   
[https://www.amazon.de/b/?](https://www.amazon.de/b/?)

**Comment by rishijash** [comment]
Thank you for letting us know. This should be fixed by now. 👍
